name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        # with:
        #   flutter-version: 'stable'  # Ensure you're using the stable channel
      # - name: Kotlin version check
      #   run: kotlin -version

      # - name: Show updated build.gradle
      #   run: cat android/build.gradle

      # - name: Update Kotlin version in build.gradle
      #   run: |
      #     (Get-Content android/build.gradle) -replace 'ext.kotlin_version = "[0-9.]*"', 'ext.kotlin_version = "2.0.0"' | Set-Content android/build.gradle

      # - name: Show updated build.gradle
      #   run: cat android/build.gradle

      # - name: Kotlin version check
      #   run: kotlin -version
      
      - name: Install dependencies
        run: flutter pub get

      - name: Decode and setup keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > android/app/key.jks
          echo "Keystore decoded and saved as android/app/key.jks"
          ls -l android/app

      # - name: Set up environment variables
      #   run: |
      #     echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
      #     echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
      #     echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV



      - name: Build APK
        run: |
          flutter build apk --release --no-shrink

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
